apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mytomcat
  namespace: default
  labels:
    app: mytomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mytomcat
  template:
    metadata:
      name: mytomcat-pod
      labels:
        app: mytomcat
    spec:  
      containers:
      - name: mytomcat
        image: tomcat:v0.0-1
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mytomcat
  namespace: default
spec:
  selector:
    app: mytomcat
  clusterIP: 10.99.99.98
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30081
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-mytomcat
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "mytomcat"
spec:
  rules:
  - host: mytomcat.master.com
    http:
      paths:
      - backend:
          serviceName: mytomcat
          servicePort: 30081
